maintps/src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\OrderRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="orders")
 * @UniqueEntity("orderNumber")
 */
class Order
{
    const EN_COURS = 0;
    const EN_ATTENTE = 1;
    const CLOTUREE = 2;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $orderNumber;

    /**
     * 
     * @ORM\Column(type="date")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=DeliveryForm::class, mappedBy="order", orphanRemoval=true)
     */
    private $deliveryForms;

    /**
     * @ORM\ManyToOne(targetEntity=Provider::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $provider;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Item::class, mappedBy="order")
     */
    private $items;

    /**
     * @ORM\ManyToMany(targetEntity=Invoice::class, inversedBy="orders")
     */
    private $invoice;

    /**
     * @ORM\Column(type="float")
     */
    private $expectedAmount;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $designation;

    /**
     * @ORM\ManyToMany(targetEntity=Account::class, inversedBy="orders")
     */
    private $account;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $expectedDeliveryDate;

    /**
     * @ORM\Column(type="string", length=1)
     * @Assert\NotBlank
     */
    private $status;

    public function __construct()
    {
        $this->deliveryForms = new ArrayCollection();
        $this->items = new ArrayCollection();
        $this->invoice = new ArrayCollection();
        $this->account = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderNumber(): ?string
    {
        return $this->orderNumber;
    }

    public function setOrderNumber(string $orderNumber): self
    {
        $this->orderNumber = $orderNumber;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|DeliveryForm[]
     */
    public function getDeliveryForms(): Collection
    {
        return $this->deliveryForms;
    }

    public function addDeliveryForm(DeliveryForm $deliveryForm): self
    {
        if (!$this->deliveryForms->contains($deliveryForm)) {
            $this->deliveryForms[] = $deliveryForm;
            $deliveryForm->setOrder($this);
        }

        return $this;
    }

    public function removeDeliveryForm(DeliveryForm $deliveryForm): self
    {
        if ($this->deliveryForms->removeElement($deliveryForm)) {
            // set the owning side to null (unless already changed)
            if ($deliveryForm->getOrder() === $this) {
                $deliveryForm->setOrder(null);
            }
        }

        return $this;
    }

    public function getProvider(): ?Provider
    {
        return $this->provider;
    }

    public function setProvider(?Provider $provider): self
    {
        $this->provider = $provider;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setOrder($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getOrder() === $this) {
                $item->setOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoice(): Collection
    {
        return $this->invoice;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoice->contains($invoice)) {
            $this->invoice[] = $invoice;
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        $this->invoice->removeElement($invoice);

        return $this;
    }

    public function getExpectedAmount(): ?float
    {
        return $this->expectedAmount;
    }

    public function setExpectedAmount(float $expectedAmount): self
    {
        $this->expectedAmount = $expectedAmount;

        return $this;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    /**
     * @return Collection|Account[]
     */
    public function getAccount(): Collection
    {
        return $this->account;
    }

    public function addAccount(Account $account): self
    {
        if (!$this->account->contains($account)) {
            $this->account[] = $account;
        }

        return $this;
    }

    public function removeAccount(Account $account): self
    {
        $this->account->removeElement($account);

        return $this;
    }

    public function getExpectedDeliveryDate(): ?\DateTimeInterface
    {
        return $this->expectedDeliveryDate;
    }

    public function setExpectedDeliveryDate(?\DateTimeInterface $expectedDeliveryDate): self
    {
        $this->expectedDeliveryDate = $expectedDeliveryDate;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getTextStatus(): ?string
    {
        switch($this->status) {
            case 0:
                return "En cours";
                break;
            case 1:
                return "En attente";
                break;
            case 2:
                return "Cloturée";
                break;
        }
        
    }
}

maintps/src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Entity\Account;
use App\Entity\Provider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('designation', TextType::class, [
                'label'     => 'Objet : ',
            ])
            ->add('expectedAmount', MoneyType::class, [
                'label'     =>  'Montant : ',
            ])
            ->add('expectedDeliveryDate', DateType::class, [
                'widget' => 'single_text',
                'label'     =>  'Date expédition : ',
            ])    
            ->add('provider', EntityType::class, [
                'class'     =>  Provider::class,
                'choice_label' => 'username',
                'label'     =>  'Fournisseur : ',
            ])   
            ->add('account', EntityType::class, [
                'class'     => Account::class,
                'choice_label'  =>  'designation',
                'label'         =>  'Compte : ',
                'multiple' => true,
                'expanded' => true,
            ])    
            ->add('Validation', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

maintps/src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use PHPUnit\Util\Json;
use App\Form\OrderType;
use App\Data\SearchOrder;
use App\Form\SearchOrderForm;
use PHP_CodeSniffer\Tokenizers\JS;
use App\Repository\OrderRepository;
use App\Repository\OptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class OrderController extends AbstractController
{
    private $orderRepository;
    private $manager;
    private $userRepository;

    public function __construct(OrderRepository $orderRepository, OptionRepository $optionRepository, EntityManagerInterface $manager)
    {
        $this->orderRepository = $orderRepository;
        $this->manager = $manager;
        $this->optionRepository = $optionRepository;
    }

    /**
     * @Route("/order/list", name="order_list")
     * @Security("is_granted('ROLE_USER')")
     */
    public function index(Request $request) : Response
    {
        $user = $this->getUser();
        $options = $user->getOptions();
        $data = new SearchOrder();
        $data->page = $request->get('page', 1);
        $form = $this->createForm(SearchOrderForm::class, $data);
        $form->handleRequest($request);
        $orders = $this->orderRepository->findSearch($data);
        if($request->get('ajax')){
            return new JsonResponse([
                'content'   =>  $this->renderView('order/_orders.html.twig', ['orders' => $orders]),
                'sorting'   =>  $this->renderView('order/_sorting.html.twig', ['orders' => $orders]),
                'pagination'   =>  $this->renderView('order/_pagination.html.twig', ['orders' => $orders]),
            ]);
        }
        return $this->render('order/list.html.twig', [
            'orders'    =>  $orders,
            'form'      =>  $form->createView(),
            'user'      =>  $user,
            'options'   =>  $options,
        ]);
    }

    /**
     * @Route("/order/processed", name="order_in_progress")
     * @Security("is_granted('ROLE_USER')")
     */
    public function orderInProgress(): Response
    {
        $orders = $this->orderRepository->inProgressOrder();

        return $this->render('order/index.html.twig', [
            'orders'    => $orders,
        ]);
    }

    /**
     * @Route("/order/create", name="order_new")
     * @Security("is_granted('ROLE_USER')")
     */
    public function orderCreate(Request $request, EntityManagerInterface $manager): Response
    {
        $order = new Order();

        $form = $this->createForm(OrderType::class, $order);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $order = $form->getData();
            $order->setuser($this->getUser());
            $order->setCreatedAt(new \DateTime('now'));

            $manager->persist($order);
            $order->setOrderNumber($this->orderRepository->findLastOrder()->getOrderNumber() + 1);
            $manager->persist($order);
            $manager->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('order/create.html.twig', [
            'form'  => $form->createView(),
        ]);
    }

    /**
     * @Route("/order/{id}", name="order_show")
     * @Security("is_granted('ROLE_USER')")
     */
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order'    => $order,
        ]);
    }

    /**
     * @Route("/order/{id}/edit", name="order_edit")
     * @Security("is_granted('ROLE_USER')")
     */
    public function edit(Order $order, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($order);
            $manager->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('order/create.html.twig', [
            'form'  => $form->createView(),
        ]);
    }
}

maintps/templates/order/_CondensedOrderList.html.twig
<div class="row">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th scope="col">Numéro</th>
                <th scope="col">Date</th>
                <th scope="col">Fournisseur</th>
                <th scope="col">Designation</th>
                <th scope="col">Date Livraison</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <th scope="row">
                        <a href="{{ path('order_show', { 'id': order.id }) }}">
                            {% set array = [] %}
                            {% for account in order.account %}
                                {% set array = array|merge([ account.letter ]) %}                             
                            {% endfor %}
                            R2{{ array|join("") }}40-{{ order.orderNumber }}
                        </a>
                    </th>
                    <td>{{ order.createdAt|date("m/d/Y") }}</td>
                    <td>{{ order.provider.username }}</td>
                    <td>{{ order.designation }}</td>
                    <td>{{ order.expectedDeliveryDate|date("m/d/Y") }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

maintps/templates/order/_filter.html.twig
<div class="">
    <h3 class="mx-auto mb-2" style="width: 80px; color: #ffff;">Filtres</h3>
    {{ form_start(form, {attr: {class: 'filter js-filter-form'}}) }}
        <div class="mt-2 d-flex">
            <div class="filterbtn">
                {{ form_row(form.numero)}}
            </div>
        </div>
        <div class="mt-2 d-flex">
            <div class="filterbtn">
                {{ form_row(form.provider)}}
            </div>
        </div>
        <div class="mt-2 d-flex">
            <div class="filterbtn">
                {{ form_row(form.user)}}
            </div>
        </div>
        <div class="mt-2 d-flex">
            <div class="filterbtn">
                {{ form_row(form.designation)}}
            </div>
        </div>
        <div class="mt-2 border border-primary rounded px-1">
            <h5>Compte</h5>
            {{ form_row(form.account)}}
        </div>
        <div class="mt-2 border border-primary rounded px-1">
            <h5>Statut</h5>
            {{ form_row(form.status)}}
        </div>
        <div class="mt-2">
            <button type="submit" class="btn btn-primary w-100">Filtrer</button>
        </div>
        
    {{ form_end(form) }}
</div>

maintps/templates/order/_orderCard.html.twig
<div class="row">
    <table class="table table-striped table-sm">
        <thead class="js-filter-sorting">
            {% include 'order/_sorting.html.twig' %}
        </thead>
        <tbody class="js-filter-content">
            {% include 'order/_orders.html.twig' %}
        </tbody>
    </table>
</div>

maintps/templates/order/_orderList.html.twig
<div class="row">
    <table class="table table-striped table-sm">
        <thead class="js-filter-sorting">
            {% include 'order/_sorting.html.twig' %}
        </thead>
        <tbody class="js-filter-content">
            {% include 'order/_orders.html.twig' %}
        </tbody>
    </table>
</div>

maintps/templates/order/_orders.html.twig
{% for order in orders %}
    <tr>
        <th scope="row">
            <a href="{{ path('order_show', { 'id': order.id }) }}">
                {% set array = [] %}
                {% for account in order.account %}
                    {% set array = array|merge([ account.letter ]) %}                             
                {% endfor %}
                R2{{ array|join("") }}40-{{ order.orderNumber }}
            </a>
        </th>
        <td class="text-center">{{ order.createdAt|date("m/d/Y") }}</td>
        <td class="text-center">{{ order.provider.username }}</td>
        <td class="text-center">{{ order.designation }}</td>
        <td class="text-center">{{ 
            order.user.firstName|first 
            ~ 
            order.user.lastName|first 
        }}</td>
        <td class="text-center">{{ order.expectedAmount }}</td>
        <td class="text-center">{{ order.expectedDeliveryDate|date("m/d/Y") }}</td>
        <td class="text-center">{{ order.textStatus }}</td>
    </tr>
{% endfor %}

maintps/templates/order/_pagination.html.twig
    {{ knp_pagination_render(orders) }}
    

maintps/templates/order/_productList.html.twig
<div class="row">
    <div class="col-3">
        <h3>Liste des Commandes</h3>
    </div>
    <div class="col-2">
        <a class="btn btn-primary btn-sm" href="{{ path('order_new') }}" role="button">Nouvelle commande</a>
    </div>
</div>
<div class="row">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th scope="col">Numéro</th>
                <th scope="col">Date</th>
                <th scope="col">Fournisseur</th>
                <th scope="col">Designation</th>
                <th scope="col">Créateur</th>
                <th scope="col">Montant</th>
                <th scope="col">Date Livraison</th>
                <th scope="col">Statut</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <th scope="row">
                        <a href="{{ path('order_show', { 'id': order.id }) }}">
                            {% set array = [] %}
                            {% for account in order.account %}
                                {% set array = array|merge([ account.letter ]) %}                             
                            {% endfor %}
                            R2{{ array|join("") }}40-{{ order.orderNumber }}
                        </a>
                    </th>
                    <td>{{ order.createdAt|date("m/d/Y") }}</td>
                    <td>{{ order.provider.username }}</td>
                    <td>{{ order.designation }}</td>
                    <td>{{ 
                        order.user.firstName|first 
                        ~ 
                        order.user.lastName|first 
                    }}</td>
                    <td>{{ order.expectedAmount }}</td>
                    <td>{{ order.expectedDeliveryDate|date("m/d/Y") }}</td>
                    <td>{{ order.textStatus }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

maintps/templates/order/_sorting.html.twig
<tr>
    <th scope="col">{{ knp_pagination_sortable(orders, 'Numéro', 'o.orderNumber') }}</th>
    <th scope="col" class="text-center">{{ knp_pagination_sortable(orders, 'Date', 'o.createdAt') }}</th>
    <th scope="col" class="text-center">{{ knp_pagination_sortable(orders, 'Fournisseur', 'p.username') }}</th>
    <th scope="col" class="text-center">Designation</th>
    <th scope="col" class="text-center">{{ knp_pagination_sortable(orders, 'Utilisateur', 'u.username') }}</th>
    <th scope="col" class="text-center">{{ knp_pagination_sortable(orders, 'Montant', 'o.expectedAmount') }}</th>
    <th scope="col" class="text-center">{{ knp_pagination_sortable(orders, 'Date Livraison', 'o.expectedDeliveryDate') }}</th>
    <th scope="col" class="text-center">{{ knp_pagination_sortable(orders, 'Statut', 'o.status') }}</th>
</tr>

maintps/templates/order/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle commande{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-8 mx-auto">
            <div class="d-flex justify-content-start">
                <h1>Nouvelle commande</h1>
            </div>
            
            {{ form(form) }}
        </div>
    </div>

{% endblock %}

maintps/templates/order/default.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="container accueil">
        <div class="row">
            <div class="col-6">
                <div class="row">
                    <div class="col-12">
                        <div class="row mt-5">
                                <div class="col-6 mb-3">
                                    <h3>Commandes en cours...</h3>
                                </div>
                            <div class="col-10">
                                <a class="col-6 btn btn-primary btn-sm" href="{{ path('order_new') }}" role="button">Nouvelle commande</a>
                                <a class="col-4 btn btn-primary btn-sm" href="{{ path('order_list') }}" role="button">Liste</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'order/_condensedOrderList.html.twig' with {orders: orders} only %}
                {{ knp_pagination_render(orders) }}
            </div>
        </div>
    </div>


{% endblock %}

maintps/templates/order/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes{% endblock %}

{% block body %}
    <main class="mt-4 js-filter">
        <div class="row">
            <aside class="col-2">
                {% include 'order/_filter.html.twig' with {form: form} only %}
            </aside>
            <article class="col-10">
                <div class="row">
                    <div class="col-3">
                        <h3>Liste des Commandes</h3>
                    </div>
                    <div class="col-2">
                        <a class="btn btn-primary btn-sm" href="{{ path('order_new') }}" role="button">Nouvelle commande</a>
                    </div>
                     <div class="col-1 offset-6">
                        {% if options.displayOrderList %}
                            <a href="{{ path('toggle_order_display', { id: options.id }) }}"><img class="orderDisplay" src="{{ asset('img/carte.png') }}" alt="carte"></a>
                        {% else %}
                            <a href="{{ path('toggle_order_display', { id: options.id } ) }}"><img class="orderDisplay" src="{{ asset('img/liste.png') }}" alt="liste"></a>
                        {% endif %} 
                    </div>
                </div>
                <div>
                    {% if options.displayOrderList == "list" %}
                        {% include 'order/_orderList.html.twig' with {orders: orders} only %}
                    {% else %}
                        {% include 'order/_orderCard.html.twig' with {orders: orders} only %}
                    {% endif %} 
                </div>
                <div class="js-filter-pagination">
                    {% include 'order/_pagination.html.twig' %}
                </div>
            </article>
        </div>
    </main>

{% endblock %}

maintps/templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande {{ order.orderNumber }}{% endblock %}

{% block body %}
    <div class="container accueil mt-3">
        <div class="row">
            <div class="col-5">
                <div class="row">
                    <div class="col-7">
                        <h4 class="titreShowOrder text-center p-1">
                            Commande
                            {% set array = [] %}
                            {% for account in order.account %}
                                {% set array = array|merge([ account.letter ]) %}                             
                            {% endfor %}
                            R2{{ array|join("") }}40-{{ order.orderNumber }}
                        </h4>
                    </div>
                    <div class="col-3">
                        <a href="{{ path('order_edit', { 'id': order.id } ) }}" type='button' class="btn btn-success">Modification</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-12">
                <div class="row mt-3">
                    <div class="col-4"><strong>Fournisseur : {{ order.provider.username }}</strong></div>
                    <div class="col-5"><strong>Désignation : </strong>{{ order.designation }}</div>
                    <div class="col-3"><strong>Montant : </strong>{{ order.expectedAmount }}</div>
                </div>
                <div class="row mt-3">
                    <div class="col-4"><strong>Date de commande : </strong>{{ order.createdAt | date("d/m/Y") }}</div>
                    <div class="col-5"><strong>Date livraison prévue : </strong>{{ order.expectedDeliveryDate | date("d/m/Y") }}</div>
                    <div class="col-3"><strong>Statut : </strong>{{ order.textStatus }}</div>
                </div>
            </div>
        </div>
        
        {# Bon de livraison et factures #}
        <div class="row">
            <div class="col-5">
                <div class="d-flex">
                    <h2 class="subTitleShowOrder col-5">Bons de livraison</h2>
                    <a class="btn btn-primary btn-sm" href="{{ path('delivery_form_new', { 'id': order.id }) }}" role="button">Ajout BL</a>
                </div>
                {% for deliveryForm in order.deliveryForms %}
                    <div class="row mt-3">
                        <div class="border border-secondary rounded">
                            
                                <p><strong>Numéro : </strong>{{ deliveryForm.deliveryFormNumber }}</p>
                                <p><strong>Date : </strong>{{ deliveryForm.deliveryFormDate | date("d/m/Y") }}</p>
                            
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-6 offset-1">
                <div class="d-flex">
                    <h2 class="subTitleShowOrder col-3">Factures</h2>
                    <a class="btn btn-primary btn-sm" href="{{ path('order_new') }}" role="button">Ajout Facture</a>
                </div>
                <div class="mt-2">
                    {% for invoice in order.invoice %}
                        <div class="border border-secondary rounded mb-2 p-2">
                            <div class="row mt-3">
                                <div class="col-4">
                                    <p><strong>Numéro : </strong>{{ invoice.invoiceNumber }}</p>
                                </div>
                                <div class="col-4">
                                    <p><strong>Date : </strong>{{ invoice.invoiceDate | date("d/m/Y") }}</p>
                                </div>
                                <div class="col-4">
                                    <p><strong>Montant : </strong>{{ invoice.amount }}€</p>
                                </div>
                            </div>
                            <div>
                                <h5>Bon de livraison : </h5>
                            </div>
                            {% for deliveryForm in invoice.deliveryForms %}
                                <div>
                                    <p>Numéro : {{ deliveryForm.deliveryFormNumber}} Date : {{ deliveryForm.deliveryDate | date("d/m/Y") }}
                                </div>
                            {% else %}
                                    <p>Aucun bon de livraison enregistré</p>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p>Aucun facture enregistrée</p>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}